### ISSUE TITLE
User Story: Reasons Section {EPIC??}

### ISSUE THREAD

**Issue by CI-Duncan** [ErfanNajimi/hackathon-project-group-3#6]
As a **site visitor** I can **see the reasons the that staying safe online is important** so that **I will use your site to learn about and implement the preventative measures described**

** Acceptance Criteria: **
* Acceptance Criteria 1: A site area containing the importance of Online Safety
* Acceptance Criteria 2: Different Areas covering different types of Online Safety (Personal: cyber bulling / identity theft : Device: Password Strength / Malware)
* Acceptance Criteria 3: Referral to preventative measures

Task
- [x] Task 1 Create area detailing why Online Safety is important
- [ ] #15
- [ ] [ ] **Cyber Bullying** Mental Health / Suicide .
- [ ] [ ] **Identity Theft** Fraud / Malicious Content posted online under your name
- [ ] [ ] **Password Strength** Access to your data / Enables ID theft 
- [ ] [ ] **Malware** Could lead to Ransomware  / Enabled ID theft
- [ ] Task 3 Create area detailing how to prevent above.
